### ISSUE TITLE
Add reference to SHA1 in DS insecurity requirement

### ISSUE THREAD

**Issue by brian-peter-dickson** [ietf-wg-dnsop/draft-ietf-dnsop-must-not-sha1#1]
Where it currently says "Validating resolvers MUST treat DS records as insecure", it should specify this applies only to SHA1.

I.e. "Validating resolvers MUST treat SHA1 DS records as insecure."

**Comment by hardaker** [comment]
Good point!  fixed and thanks.  See 310f7a9
